# Тензоры

Тензор - специализированная структура данных, которая очень похожа на массивы и матрицы. В PyTorch мы используем тензоры для кодирования входов и выходов модели, а также ее параметров.

Тензоры похожи на массивы NumPy, за исключением того, что тензоры могут работать на GPU или другом специализированном оборудовании для ускорения вычислений.

In [1]:
import torch
import numpy as np

<h2>Инициализация тензоров</h2>

In [2]:
# Напрямую из данных
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)

In [3]:
# Из массивов numpy (и наоборот, тензоры в массивы numpy)
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [4]:
# Из другого тензора 
# Новый тензор сохраняет свойства (форму, тип данных) тензора-аргумента, если они не переопределены явно.
x_ones = torch.ones_like(x_data)  # сохраняет свойства x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float)  # переопределяет тип данных x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.9327, 0.2186],
        [0.1775, 0.5615]]) 



In [5]:
# Со случайными или постоянными значениями
# shape - кортеж размерностей тензора. В приведенных ниже функциях он определяет размерность выходного тензора
shape = (2, 3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.5240, 0.8208, 0.8891],
        [0.3506, 0.4435, 0.9448]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


<h2>Атрибуты тензора</h2>

Атрибуты тензора описывают его размерность, тип данных, и устройство, на которых он хранится.

In [6]:
tensor = torch.rand(3, 4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


<h2>Операции с тензорами</h2>

Больше 100 операций с тензорами, включая транспонирование, индексирование, нарезку, математические операции, линейную алгебру случайную выборку и многое другое описано [здесь](https://pytorch.org/docs/stable/torch.html)

Каждая из них может быть выполнена на GPU (обычно с более высокой скоростью, чем на CPU).

In [7]:
# Перемещаем наш тензор на GPU, если это возможно
if torch.cuda.is_available():
    tensor = tensor.to('cuda')
    print(f"Device tensor is stored on {tensor.device}")

Device tensor is stored on cuda:0


<h3>Стандартные операции индексации и слайсинга</h3>

In [8]:
tensor = torch.ones(4, 4)
tensor[:, 1] = 0
tensor

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

<h3>Объединение тензоров</h3>

Можно использовать `torch.cat` чтобы объединить последовательность тензоров по заданному измерению.

Также существует [torch.stack](https://pytorch.org/docs/stable/generated/torch.stack.html), другая операция по объединению тензоров, которая мало чем отличается от torch.cat.

In [9]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
t1

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])

<h3>Умножение тензоров</h3>

In [10]:
# Здесь вычисляется изменение по элементам
print(f"tensor.mul(tensor) \n {tensor.mul(tensor)} \n")
# Альтернативный синтаксис
print(f"tensor * tensor \n {tensor * tensor}")

tensor.mul(tensor) 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor * tensor 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [11]:
# Возвращает представление матрицу с обратной размерностью
# Если n это число размерностей в x, x.T эквивалентно x.permute(n-1, n-2, ..., 0)
print(tensor.T)
# Здесь вычисляется матричное умножение между двумя тензорами
print(f"tensor.matmul(tensor.T) \n {tensor.matmul(tensor.T)} \n")
# Альтернативный синтаксис
print(f"tensor @ tensor.T \n {tensor @ tensor.T}")
# Не понял, почему они в сумме дают тензор из троек

tensor([[1., 1., 1., 1.],
        [0., 0., 0., 0.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor.matmul(tensor.T) 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]) 

tensor @ tensor.T 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])


<h3>Мутабельные операции (in-place)</h3>

Операции, имеющие суффикс \_, являются мутабельными (in_place). Например, x.copy\_(y), x.t\_() изменят x

In [12]:
print(tensor, "\n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


Примечание: мутабельные операции сохраняют немнго памяти, но могут создать проблему при вычислении производных из-за немедленной потери памяти. Поэтому их использование не рекомендуется

## Мостик с NumPy

Тензоры на CPU и массивы NumPy могут совместно использовать свои базовые ячейки памяти, и изменение одного из них приведет к изменению другого

### Тензор в массив NumPy

In [13]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


Изменение в тензоре отражается на массив numpy

In [14]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


### NumPy массив в тензор

In [15]:
n = np.ones(5)
t = torch.from_numpy(n)

Изменения в массиве numpy отражаются на тензоре

In [16]:
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
